version: '3.4'

services:
  db:
    image: rest-api-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_width_asp_net
    ports:
      - 3308:3306
    networks:
      - local-network
      
  rest-api:
    image: rest-api
    build:
      context: .
      dockerfile: REST_API/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 44300:80
    depends_on:
      - db
    networks:
      - local-network
networks:
  local-network:
    driver: bridge